Search.appendIndex(
    [
                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command",
            "name": "Command",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AgetActionClause\u0028\u0029",
            "name": "getActionClause",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#method_getActionClause"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AgetActor\u0028\u0029",
            "name": "getActor",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#method_getActor"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AgetActee\u0028\u0029",
            "name": "getActee",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#method_getActee"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AsetActor\u0028\u0029",
            "name": "setActor",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#method_setActor"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AsetActee\u0028\u0029",
            "name": "setActee",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#method_setActee"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AsetAction\u0028\u0029",
            "name": "setAction",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#method_setAction"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ADEPENDS_ON",
            "name": "DEPENDS_ON",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_DEPENDS_ON"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ANOT_DEPENDS_ON",
            "name": "NOT_DEPENDS_ON",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_NOT_DEPENDS_ON"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ARELATES_TO",
            "name": "RELATES_TO",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_RELATES_TO"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ANOT_RELATES_TO",
            "name": "NOT_RELATES_TO",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_NOT_RELATES_TO"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ACHILD",
            "name": "CHILD",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_CHILD"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ANOT_CHILD",
            "name": "NOT_CHILD",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_NOT_CHILD"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ADONE",
            "name": "DONE",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_DONE"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003ANOT_DONE",
            "name": "NOT_DONE",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_NOT_DONE"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003AMOVE",
            "name": "MOVE",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#constant_MOVE"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Command\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Command.html#property_data"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandEncoder",
            "name": "CommandEncoder",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandEncoder.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decodes\u0020a\u0020string\u0020into\u0020PHP\u0020data.",
            "url": "classes/AKlump-Taskcamp-API-CommandEncoder.html#method_decode"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandEncoder\u003A\u003AsupportsEncoding\u0028\u0029",
            "name": "supportsEncoding",
            "summary": "Checks\u0020whether\u0020the\u0020serializer\u0020can\u0020encode\u0020to\u0020given\u0020format.",
            "url": "classes/AKlump-Taskcamp-API-CommandEncoder.html#method_supportsEncoding"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandEncoder\u003A\u003AsupportsDecoding\u0028\u0029",
            "name": "supportsDecoding",
            "summary": "Checks\u0020whether\u0020the\u0020deserializer\u0020can\u0020decode\u0020from\u0020given\u0020format.",
            "url": "classes/AKlump-Taskcamp-API-CommandEncoder.html#method_supportsDecoding"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Encodes\u0020data\u0020into\u0020the\u0020given\u0020format.",
            "url": "classes/AKlump-Taskcamp-API-CommandEncoder.html#method_encode"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface",
            "name": "CommandInterface",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface\u003A\u003AgetActor\u0028\u0029",
            "name": "getActor",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html#method_getActor"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface\u003A\u003AgetActee\u0028\u0029",
            "name": "getActee",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html#method_getActee"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface\u003A\u003AgetActionClause\u0028\u0029",
            "name": "getActionClause",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html#method_getActionClause"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface\u003A\u003AsetActor\u0028\u0029",
            "name": "setActor",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html#method_setActor"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface\u003A\u003AsetActee\u0028\u0029",
            "name": "setActee",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html#method_setActee"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\CommandInterface\u003A\u003AsetActionClause\u0028\u0029",
            "name": "setActionClause",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-CommandInterface.html#method_setActionClause"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity",
            "name": "Entity",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Get\u0020the\u0020entity\u0020type.",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getType"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetProperties\u0028\u0029",
            "name": "getProperties",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getProperties"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Get\u0020the\u0020data\u0020associated\u0020with\u0020the\u0020entity.",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getData"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Get\u0020the\u0020title\u0020of\u0020the\u0020entity.",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getTitle"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Get\u0020the\u0020body\u0020portion\u0020of\u0020the\u0020entity.",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getBody"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AsetType\u0028\u0029",
            "name": "setType",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_setType"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AsetProperties\u0028\u0029",
            "name": "setProperties",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_setProperties"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_setData"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_setTitle"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AsetBody\u0028\u0029",
            "name": "setBody",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_setBody"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AjsonSerialize\u0028\u0029",
            "name": "jsonSerialize",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_jsonSerialize"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetDatum\u0028\u0029",
            "name": "getDatum",
            "summary": "Get\u0020a\u0020datum\u0020value\u0020or\u0020default\u0020value.",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getDatum"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003AgetProperty\u0028\u0029",
            "name": "getProperty",
            "summary": "Get\u0020the\u0020value\u0020of\u0020a\u0020property\u0020or\u0020default\u0020if\u0020property\u0020does\u0020not\u0020exist.",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#method_getProperty"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\Entity\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-Entity.html#property_data"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityEncoder",
            "name": "EntityEncoder",
            "summary": "An\u0020encoder\/decoder\u0020for\u0020application\/prs.taskcamp.entity\u0020MIME\u0020types.",
            "url": "classes/AKlump-Taskcamp-API-EntityEncoder.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityEncoder\u003A\u003Aencode\u0028\u0029",
            "name": "encode",
            "summary": "Encodes\u0020data\u0020into\u0020the\u0020given\u0020format.",
            "url": "classes/AKlump-Taskcamp-API-EntityEncoder.html#method_encode"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityEncoder\u003A\u003AsupportsEncoding\u0028\u0029",
            "name": "supportsEncoding",
            "summary": "Checks\u0020whether\u0020the\u0020serializer\u0020can\u0020encode\u0020to\u0020given\u0020format.",
            "url": "classes/AKlump-Taskcamp-API-EntityEncoder.html#method_supportsEncoding"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityEncoder\u003A\u003AsupportsDecoding\u0028\u0029",
            "name": "supportsDecoding",
            "summary": "Checks\u0020whether\u0020the\u0020deserializer\u0020can\u0020decode\u0020from\u0020given\u0020format.",
            "url": "classes/AKlump-Taskcamp-API-EntityEncoder.html#method_supportsDecoding"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityEncoder\u003A\u003Adecode\u0028\u0029",
            "name": "decode",
            "summary": "Decodes\u0020a\u0020string\u0020into\u0020PHP\u0020data.",
            "url": "classes/AKlump-Taskcamp-API-EntityEncoder.html#method_decode"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityEncoder\u003A\u003ATYPE",
            "name": "TYPE",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityEncoder.html#constant_TYPE"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface",
            "name": "EntityInterface",
            "summary": "Interface\u0020EntityInterface.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetBody\u0028\u0029",
            "name": "getBody",
            "summary": "Get\u0020the\u0020body\u0020portion\u0020of\u0020the\u0020entity.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getBody"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "Get\u0020the\u0020data\u0020associated\u0020with\u0020the\u0020entity.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getData"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetDatum\u0028\u0029",
            "name": "getDatum",
            "summary": "Get\u0020a\u0020datum\u0020value\u0020or\u0020default\u0020value.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getDatum"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetProperties\u0028\u0029",
            "name": "getProperties",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getProperties"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetProperty\u0028\u0029",
            "name": "getProperty",
            "summary": "Get\u0020the\u0020value\u0020of\u0020a\u0020property\u0020or\u0020default\u0020if\u0020property\u0020does\u0020not\u0020exist.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getProperty"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Get\u0020the\u0020title\u0020of\u0020the\u0020entity.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getTitle"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "Get\u0020the\u0020entity\u0020type.",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_getType"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AsetBody\u0028\u0029",
            "name": "setBody",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_setBody"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AsetData\u0028\u0029",
            "name": "setData",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_setData"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AsetProperties\u0028\u0029",
            "name": "setProperties",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_setProperties"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AsetTitle\u0028\u0029",
            "name": "setTitle",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_setTitle"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntityInterface\u003A\u003AsetType\u0028\u0029",
            "name": "setType",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-EntityInterface.html#method_setType"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntitySerializer",
            "name": "EntitySerializer",
            "summary": "A\u0020configured\u0020serializer\u0020class\u0020for\u0020Entity.",
            "url": "classes/AKlump-Taskcamp-API-EntitySerializer.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\EntitySerializer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/AKlump-Taskcamp-API-EntitySerializer.html#method___construct"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\MimeTypes",
            "name": "MimeTypes",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-MimeTypes.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\MimeTypes\u003A\u003AENTITY",
            "name": "ENTITY",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-MimeTypes.html#constant_ENTITY"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\MimeTypes\u003A\u003ACOMMAND",
            "name": "COMMAND",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-MimeTypes.html#constant_COMMAND"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API\\SyntaxErrorException",
            "name": "SyntaxErrorException",
            "summary": "",
            "url": "classes/AKlump-Taskcamp-API-SyntaxErrorException.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp\\API",
            "name": "API",
            "summary": "",
            "url": "namespaces/aklump-taskcamp-api.html"
        },                {
            "fqsen": "\\AKlump\\Taskcamp",
            "name": "Taskcamp",
            "summary": "",
            "url": "namespaces/aklump-taskcamp.html"
        },                {
            "fqsen": "\\AKlump",
            "name": "AKlump",
            "summary": "",
            "url": "namespaces/aklump.html"
        }            ]
);
